package com.jgp.config;

import org.cache2k.extra.spring.SpringCache2kCacheManager;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.concurrent.TimeUnit;

@Configuration
@EnableCaching
public class CacheConfig {

    @Bean
    public CacheManager cacheManager() {
        return new SpringCache2kCacheManager()
                .addCaches(b -> b.name("operationalCounties")
                        .expireAfterWrite(5, TimeUnit.HOURS)
                        .entryCapacity(5))
                .addCaches(b -> b.name("highLevelSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loanDisbursedByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("countySummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loanedBusinessesByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loanDisbursedByIndustrySectorSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loanDisbursedByIndustrySegmentSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loanDisbursedTopFourPartnersSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loanDisbursedTopFourCountiesSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("businessTrainedTopFourCountiesSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("businessOwnersTrainedByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("pLWDAndRefugeeBusinessOwnersTrainedByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("disabledBusinessOwnersTrainedByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("refugeeBusinessOwnersTrainedByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loanDisbursedByPipelineSourceSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("mentorshipByGivenFieldSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loansDisbursedByQualitySummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("systemUserLoginSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("taNeedsByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("businessCategoryByCountySummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("taTrainingBySectorSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))

                .addCaches(b -> b.name("loansDisbursedByLoanProductSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("outcomeMonitoringSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("participantsEmployeesSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("taTrainingBySegmentSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("participantsMentorshipDeliveryModeSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("trainingByPartnerByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loanDisbursedByLoanProductByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("lastThreeYearsAccessedLoanPerPartnerSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("lastThreeYearsAccessedLoanAmountPerPartnerYearly")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("lastThreeYearsAccessedLoansCountPerPartnerYearly")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("lastThreeYearsTrainedBusinessesPerPartnerYearly")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("taTypeTrainedBusinesses")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loansAccessedVsOutStandingByPartnerSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("loansAccessedVsOutStandingByGenderSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("dataSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("dataSummaryMap")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30))
                .addCaches(b -> b.name("performanceSummary")
                        .expireAfterWrite(1, TimeUnit.HOURS)
                        .entryCapacity(30));
    }
}