package com.jgp.infrastructure.bulkimport.populator.monitoring;

import com.jgp.infrastructure.bulkimport.constants.TemplatePopulateImportConstants;
import com.jgp.infrastructure.bulkimport.data.GlobalEntityType;
import com.jgp.infrastructure.bulkimport.data.MonitoringConstants;
import com.jgp.infrastructure.bulkimport.populator.AbstractWorkbookPopulator;
import com.jgp.infrastructure.bulkimport.populator.TemplateGuidePopulator;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

@Slf4j
public class MonitoringWorkbookPopulator extends AbstractWorkbookPopulator {
    @Override
    public void populate(Workbook workbook) {
        Sheet monitoringSheet = workbook.createSheet("Monitoring");
        setLayout(monitoringSheet);
        TemplateGuidePopulator.populateGuide(workbook, GlobalEntityType.MONITORING_IMPORT_TEMPLATE);
    }

    private void setLayout(Sheet worksheet) {
        Row rowHeader = worksheet.createRow(TemplatePopulateImportConstants.ROWHEADER_INDEX);
        rowHeader.setHeight(TemplatePopulateImportConstants.ROW_HEADER_HEIGHT);
        worksheet.setColumnWidth(MonitoringConstants.SURVEY_DATE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SURVEY_LANGUAGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.CONSENTED_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LOCATION_LATITUDE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LOCATION_LONGITUDE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.JGP_ID_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.AGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.GENDER_CATEGORY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SEGMENT_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.PARTNER_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.GENDER_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.REGION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COUNTY_NAME_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_SETTING_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_AGE_CATEGORY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.GROUP_MEMBERSHIP_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.EDUCATION_LEVEL_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_AGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.REGULAR_EMPLOYEES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.CASUAL_EMPLOYEES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.HOUSEHOLD_INCOME_CHANGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.FINANCIAL_STABILITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.QUALITY_OF_LIFE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.EMPOWERMENT_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.VOICE_IN_COMMUNITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.RESPECT_IN_COMMUNITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.RELIABLE_INCOME_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.REPUTABLE_WORK_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SENSE_OF_PURPOSE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_SECTOR_GROWTH_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COMMUNITY_GROWTH_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.WORK_OPPORTUNITIES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.INCOME_REGULARITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.INCOME_SUFFICIENCY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.INCOME_PREDICTABILITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.FINANCIAL_SECURITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COMMUNITY_GROUPS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LEADERSHIP_ROLE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.DECISION_MAKING_CONFIDENCE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COMMUNITY_CHANGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COMMUNITY_ISSUES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_EDUCATION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_RELATIONSHIPS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_BUSINESS_TYPE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_INCOME_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_HOUSING_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_HEALTHCARE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_WATER_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_FOOD_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_NUTRITION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_LIFE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_INFORMATION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_LEISURE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.JGP_INTERVENTIONS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.TECHNICAL_TRAINING_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.NEW_PRACTICES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.IMPROVED_PRACTICES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.TRAINING_IMPROVEMENTS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_CHANGES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.PROFITABILITY_GROWTH_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.REVENUE_CHANGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LOAN_APPLICATION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.NUMBER_OF_LOANS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LOAN_PLATFORM_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.EXTERNAL_FINANCING_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.FINANCING_SOURCES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.JGP_IMPACT_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.CHANGES_WITHOUT_JGP_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.MARKET_ACCESS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_OPPORTUNITIES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.MARKET_CHALLENGES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);

        writeString(MonitoringConstants.SURVEY_DATE_COL, rowHeader, "Survey Date* (yyyy-MM-dd example:2000-04-20)");
        setDateColumnFormat(worksheet.getWorkbook(), TemplatePopulateImportConstants.MONITORING_SHEET_NAME, MonitoringConstants.SURVEY_DATE_COL);
        writeString(MonitoringConstants.SURVEY_LANGUAGE_COL, rowHeader, "Survey Language*");
        writeString(MonitoringConstants.CONSENTED_COL, rowHeader, "Consented* (Yes|No)");
        writeString(MonitoringConstants.LOCATION_LATITUDE_COL, rowHeader, "Location Latitude");
        writeString(MonitoringConstants.LOCATION_LONGITUDE_COL, rowHeader, "Location Longitude");
        writeString(MonitoringConstants.JGP_ID_COL, rowHeader, "JGP ID (National ID/Passport/Alien Number)*");
        writeString(MonitoringConstants.AGE_COL, rowHeader, "Age*");
        writeString(MonitoringConstants.GENDER_CATEGORY_COL, rowHeader, "Gender Category* (Men 36+|Young Women|Young Men|Women 36+)");
        writeString(MonitoringConstants.SEGMENT_COL, rowHeader, "Segment (Micro|SME)*");
        writeString(MonitoringConstants.PARTNER_COL, rowHeader, "Partner* (KEPSA|PBP|KNCCI|4G|GROOTS|GBF|Don't Know)");
        writeString(MonitoringConstants.GENDER_COL, rowHeader, "Gender* (MALE|FEMALE|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.REGION_COL, rowHeader, "Region* (Central|Coast|Lower Eastern|Nairobi|North Eastern|North Rift|South Rift|Nyanza|Upper Eastern|Western)");
        writeString(MonitoringConstants.COUNTY_NAME_COL, rowHeader, "County Name* (Valid county name)");
        writeString(MonitoringConstants.BUSINESS_SETTING_COL, rowHeader, "Business Setting* (Urban|Rural|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.BUSINESS_AGE_CATEGORY_COL, rowHeader, "Business Age Category* (10+ Years|1-5 Years|6-10 Years)");
        writeString(MonitoringConstants.GROUP_MEMBERSHIP_COL, rowHeader, "Group Membership (Persons with disability|Refugee|None of the above|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.EDUCATION_LEVEL_COL, rowHeader, "Education Level (No formal education|Primary school|Secondary school|Tertiary education|College|certificate/diploma|Graduate degree|ost graduate degree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.BUSINESS_AGE_COL, rowHeader, "Business Age");
        writeString(MonitoringConstants.REGULAR_EMPLOYEES_COL, rowHeader, "Regular Employees");
        writeString(MonitoringConstants.CASUAL_EMPLOYEES_COL, rowHeader, "Casual Employees");
        writeString(MonitoringConstants.HOUSEHOLD_INCOME_CHANGE_COL, rowHeader, "Household Income Change (Increased a lot|Increased|Stayed the same|Decreased|Decreased a lot|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.FINANCIAL_STABILITY_COL, rowHeader, "Financial Stability (Greatly improved|Somewhat improved|No change|Somewhat worse|Significantly declined|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.QUALITY_OF_LIFE_COL, rowHeader, "Quality Of Life (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.EMPOWERMENT_COL, rowHeader, "Empowerment (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.VOICE_IN_COMMUNITY_COL, rowHeader, "Voice In Community (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.RESPECT_IN_COMMUNITY_COL, rowHeader, "Respect In Community (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.RELIABLE_INCOME_COL, rowHeader, "Reliable Income (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.REPUTABLE_WORK_COL, rowHeader, "Reputable Work (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SENSE_OF_PURPOSE_COL, rowHeader, "Sense Of Purpose (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.BUSINESS_SECTOR_GROWTH_COL, rowHeader, "Business Sector Growth (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.COMMUNITY_GROWTH_COL, rowHeader, "Community Growth (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.WORK_OPPORTUNITIES_COL, rowHeader, "Work Opportunities (Strongly Disagree|Disagree|Neutral|Agree|Strongly Agree|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.INCOME_REGULARITY_COL, rowHeader, "Income Regularity (Every week|At least once every two weeks|Once a month|Occasionally (less than once a month)|Not at all|Don't know|Refused)");
        writeString(MonitoringConstants.INCOME_SUFFICIENCY_COL, rowHeader, "Income Sufficiency (Always|Most of the time|Sometimes|Rarely|Never|Don't know|Refused)");
        writeString(MonitoringConstants.INCOME_PREDICTABILITY_COL, rowHeader, "Income Predictability (Very predictable|Somewhat predictable|Not predictable at all|Don't know|Refused)");
        writeString(MonitoringConstants.FINANCIAL_SECURITY_COL, rowHeader, "Financial Security (Not at all secure|Slightly secure|Moderately secure|Secure|Very secure|Don't know|Refused)");
        writeString(MonitoringConstants.COMMUNITY_GROUPS_COL, rowHeader, "Community Groups (Business or farmer association|Women's self-help group|NGO|Religious group|Political party|Village development committee|Local governance committee|Other village committee|Cooperative|Other [specify]|None of the above|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.LEADERSHIP_ROLE_COL, rowHeader, "Leadership Role (Yes|No|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.DECISION_MAKING_CONFIDENCE_COL, rowHeader, "Decision Making Confidence (Yes|No|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.COMMUNITY_CHANGE_COL, rowHeader, "Community Change (Yes- very easily|Yes- fairly easily|Yes- but with a little difficulty|Yes- but with a great deal of difficulty|No- not at all|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.COMMUNITY_ISSUES_COL, rowHeader, "Community Issues");
        writeString(MonitoringConstants.SATISFACTION_EDUCATION_COL, rowHeader, "Satisfaction Education (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_RELATIONSHIPS_COL, rowHeader, "Satisfaction Relationships (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_BUSINESS_TYPE_COL, rowHeader, "Satisfaction Business Type (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_INCOME_COL, rowHeader, "Satisfaction Income (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_HOUSING_COL, rowHeader, "Satisfaction Housing (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_HEALTHCARE_COL, rowHeader, "Satisfaction Healthcare (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_WATER_COL, rowHeader, "Satisfaction Water (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_FOOD_COL, rowHeader, "Satisfaction Food (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_NUTRITION_COL, rowHeader, "Satisfaction Nutrition (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_LIFE_COL, rowHeader, "Satisfaction Life (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_INFORMATION_COL, rowHeader, "Satisfaction Information (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.SATISFACTION_LEISURE_COL, rowHeader, "Satisfaction Leisure (Very Dissatisfied|Dissatisfied|Neutral|Satisfied|Very Satisfied|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.JGP_INTERVENTIONS_COL, rowHeader, "JGP Interventions");
        writeString(MonitoringConstants.TECHNICAL_TRAINING_COL, rowHeader, "Technical Training");
        writeString(MonitoringConstants.NEW_PRACTICES_COL, rowHeader, "New Practices");
        writeString(MonitoringConstants.IMPROVED_PRACTICES_COL, rowHeader, "Improved Practices");
        writeString(MonitoringConstants.TRAINING_IMPROVEMENTS_COL, rowHeader, "Training Improvements");
        writeString(MonitoringConstants.BUSINESS_CHANGES_COL, rowHeader, "Business Changes (Employed more regular employees|Employed more casual employees [new work]|Change in revenue|Opened additional business [improved work]|Remained afloat [sustained work]|Other [specify]|None [has not observed any changes]|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.PROFITABILITY_GROWTH_COL, rowHeader, "Profitability Growth (Significant increase|Moderate increase|No significant change|Decrease|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.REVENUE_CHANGE_COL, rowHeader, "Revenue Change");
        writeString(MonitoringConstants.LOAN_APPLICATION_COL, rowHeader, "Loan Application (Yes|No|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.NUMBER_OF_LOANS_COL, rowHeader, "Number Of Loans");
        writeString(MonitoringConstants.LOAN_PLATFORM_COL, rowHeader, "Loan Platform (USSD|Lending system|Physical visit|Other [specify]|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.EXTERNAL_FINANCING_COL, rowHeader, "External Financing (Yes|No|REFUSED)");
        writeString(MonitoringConstants.FINANCING_SOURCES_COL, rowHeader, "Financing Sources");
        writeString(MonitoringConstants.JGP_IMPACT_COL, rowHeader, "JGP Impact (Not at all|To a very small extent|To a small extent|To a moderate extent|To a great extent|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.CHANGES_WITHOUT_JGP_COL, rowHeader, "Changes Without JGP (Yes|No|DON'T KNOW|REFUSED)");
        writeString(MonitoringConstants.MARKET_ACCESS_COL, rowHeader, "Market Access");
        writeString(MonitoringConstants.BUSINESS_OPPORTUNITIES_COL, rowHeader, "Business Opportunities");
        writeString(MonitoringConstants.MARKET_CHALLENGES_COL, rowHeader, "Market Challenges");
    }
}
