package com.jgp.infrastructure.bulkimport.populator.monitoring;

import com.jgp.infrastructure.bulkimport.constants.TemplatePopulateImportConstants;
import com.jgp.infrastructure.bulkimport.data.MonitoringConstants;
import com.jgp.infrastructure.bulkimport.populator.AbstractWorkbookPopulator;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

@Slf4j
public class MonitoringWorkbookPopulator extends AbstractWorkbookPopulator {
    @Override
    public void populate(Workbook workbook) {
        Sheet monitoringSheet = workbook.createSheet("Monitoring");
        setLayout(monitoringSheet);
    }

    private void setLayout(Sheet worksheet) {
        Row rowHeader = worksheet.createRow(TemplatePopulateImportConstants.ROWHEADER_INDEX);
        rowHeader.setHeight(TemplatePopulateImportConstants.ROW_HEADER_HEIGHT);
        worksheet.setColumnWidth(MonitoringConstants.SURVEY_DATE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SURVEY_LANGUAGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.CONSENTED_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LOCATION_LATITUDE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LOCATION_LONGITUDE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.JGP_ID_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.AGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.GENDER_CATEGORY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SEGMENT_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.PARTNER_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.GENDER_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.REGION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COUNTY_CODE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COUNTY_NAME_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_SETTING_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_AGE_CATEGORY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.GROUP_MEMBERSHIP_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.EDUCATION_LEVEL_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_AGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.REGULAR_EMPLOYEES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.CASUAL_EMPLOYEES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.HOUSEHOLD_INCOME_CHANGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.FINANCIAL_STABILITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.QUALITY_OF_LIFE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.EMPOWERMENT_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.VOICE_IN_COMMUNITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.RESPECT_IN_COMMUNITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.RELIABLE_INCOME_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.REPUTABLE_WORK_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SENSE_OF_PURPOSE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_SECTOR_GROWTH_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COMMUNITY_GROWTH_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.WORK_OPPORTUNITIES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.INCOME_REGULARITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.INCOME_SUFFICIENCY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.INCOME_PREDICTABILITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.FINANCIAL_SECURITY_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COMMUNITY_GROUPS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LEADERSHIP_ROLE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.DECISION_MAKING_CONFIDENCE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COMMUNITY_CHANGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.COMMUNITY_ISSUES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_EDUCATION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_RELATIONSHIPS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_BUSINESS_TYPE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_INCOME_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_HOUSING_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_HEALTHCARE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_WATER_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_FOOD_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_NUTRITION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_LIFE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_INFORMATION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.SATISFACTION_LEISURE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.JGP_INTERVENTIONS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.TECHNICAL_TRAINING_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.NEW_PRACTICES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.IMPROVED_PRACTICES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.TRAINING_IMPROVEMENTS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_CHANGES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.PROFITABILITY_GROWTH_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.REVENUE_CHANGE_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LOAN_APPLICATION_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.NUMBER_OF_LOANS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.LOAN_PLATFORM_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.EXTERNAL_FINANCING_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.FINANCING_SOURCES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.JGP_IMPACT_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.CHANGES_WITHOUT_JGP_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.MARKET_ACCESS_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.BUSINESS_OPPORTUNITIES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);
        worksheet.setColumnWidth(MonitoringConstants.MARKET_CHALLENGES_COL, TemplatePopulateImportConstants.MEDIUM_COL_SIZE);

        writeString(MonitoringConstants.SURVEY_DATE_COL, rowHeader, "Survey Date (yyyy-MM-dd)");
        writeString(MonitoringConstants.SURVEY_LANGUAGE_COL, rowHeader, "Survey Language");
        writeString(MonitoringConstants.CONSENTED_COL, rowHeader, "Consented (Yes/No)");
        writeString(MonitoringConstants.LOCATION_LATITUDE_COL, rowHeader, "Location Latitude");
        writeString(MonitoringConstants.LOCATION_LONGITUDE_COL, rowHeader, "Location Longitude");
        writeString(MonitoringConstants.JGP_ID_COL, rowHeader, "JGP ID (National ID/Passport/Alien Number)*");
        writeString(MonitoringConstants.AGE_COL, rowHeader, "Age");
        writeString(MonitoringConstants.GENDER_CATEGORY_COL, rowHeader, "Gender Category");
        writeString(MonitoringConstants.SEGMENT_COL, rowHeader, "Segment");
        writeString(MonitoringConstants.PARTNER_COL, rowHeader, "Partner");
        writeString(MonitoringConstants.GENDER_COL, rowHeader, "Gender");
        writeString(MonitoringConstants.REGION_COL, rowHeader, "Region");
        writeString(MonitoringConstants.COUNTY_CODE_COL, rowHeader, "County Code");
        writeString(MonitoringConstants.COUNTY_NAME_COL, rowHeader, "County Name");
        writeString(MonitoringConstants.BUSINESS_SETTING_COL, rowHeader, "Business Setting");
        writeString(MonitoringConstants.BUSINESS_AGE_CATEGORY_COL, rowHeader, "Business Age Category");
        writeString(MonitoringConstants.GROUP_MEMBERSHIP_COL, rowHeader, "Group Membership");
        writeString(MonitoringConstants.EDUCATION_LEVEL_COL, rowHeader, "Education Level");
        writeString(MonitoringConstants.BUSINESS_AGE_COL, rowHeader, "Business Age");
        writeString(MonitoringConstants.REGULAR_EMPLOYEES_COL, rowHeader, "Regular Employees");
        writeString(MonitoringConstants.CASUAL_EMPLOYEES_COL, rowHeader, "Casual Employees");
        writeString(MonitoringConstants.HOUSEHOLD_INCOME_CHANGE_COL, rowHeader, "Household Income Change");
        writeString(MonitoringConstants.FINANCIAL_STABILITY_COL, rowHeader, "Financial Stability");
        writeString(MonitoringConstants.QUALITY_OF_LIFE_COL, rowHeader, "Quality Of Life");
        writeString(MonitoringConstants.EMPOWERMENT_COL, rowHeader, "Empowerment");
        writeString(MonitoringConstants.VOICE_IN_COMMUNITY_COL, rowHeader, "Voice In Community");
        writeString(MonitoringConstants.RESPECT_IN_COMMUNITY_COL, rowHeader, "Respect In Community");
        writeString(MonitoringConstants.RELIABLE_INCOME_COL, rowHeader, "Reliable Income");
        writeString(MonitoringConstants.REPUTABLE_WORK_COL, rowHeader, "Reputable Work");
        writeString(MonitoringConstants.SENSE_OF_PURPOSE_COL, rowHeader, "Sense Of Purpose");
        writeString(MonitoringConstants.BUSINESS_SECTOR_GROWTH_COL, rowHeader, "Business Sector Growth");
        writeString(MonitoringConstants.COMMUNITY_GROWTH_COL, rowHeader, "Community Growth");
        writeString(MonitoringConstants.WORK_OPPORTUNITIES_COL, rowHeader, "Work Opportunities");
        writeString(MonitoringConstants.INCOME_REGULARITY_COL, rowHeader, "Income Regularity");
        writeString(MonitoringConstants.INCOME_SUFFICIENCY_COL, rowHeader, "Income Sufficiency");
        writeString(MonitoringConstants.INCOME_PREDICTABILITY_COL, rowHeader, "Income Predictability");
        writeString(MonitoringConstants.FINANCIAL_SECURITY_COL, rowHeader, "Financial Security");
        writeString(MonitoringConstants.COMMUNITY_GROUPS_COL, rowHeader, "Community Groups");
        writeString(MonitoringConstants.LEADERSHIP_ROLE_COL, rowHeader, "Leadership Role");
        writeString(MonitoringConstants.DECISION_MAKING_CONFIDENCE_COL, rowHeader, "Decision Making Confidence");
        writeString(MonitoringConstants.COMMUNITY_CHANGE_COL, rowHeader, "Community Change");
        writeString(MonitoringConstants.COMMUNITY_ISSUES_COL, rowHeader, "Community Issues");
        writeString(MonitoringConstants.SATISFACTION_EDUCATION_COL, rowHeader, "Satisfaction Education");
        writeString(MonitoringConstants.SATISFACTION_RELATIONSHIPS_COL, rowHeader, "Satisfaction Relationships");
        writeString(MonitoringConstants.SATISFACTION_BUSINESS_TYPE_COL, rowHeader, "Satisfaction Business Type");
        writeString(MonitoringConstants.SATISFACTION_INCOME_COL, rowHeader, "Satisfaction Income");
        writeString(MonitoringConstants.SATISFACTION_HOUSING_COL, rowHeader, "Satisfaction Housing");
        writeString(MonitoringConstants.SATISFACTION_HEALTHCARE_COL, rowHeader, "Satisfaction Healthcare");
        writeString(MonitoringConstants.SATISFACTION_WATER_COL, rowHeader, "Satisfaction Water");
        writeString(MonitoringConstants.SATISFACTION_FOOD_COL, rowHeader, "Satisfaction Food");
        writeString(MonitoringConstants.SATISFACTION_NUTRITION_COL, rowHeader, "Satisfaction Nutrition");
        writeString(MonitoringConstants.SATISFACTION_LIFE_COL, rowHeader, "Satisfaction Life");
        writeString(MonitoringConstants.SATISFACTION_INFORMATION_COL, rowHeader, "Satisfaction Information");
        writeString(MonitoringConstants.SATISFACTION_LEISURE_COL, rowHeader, "Satisfaction Leisure");
        writeString(MonitoringConstants.JGP_INTERVENTIONS_COL, rowHeader, "JGP Interventions");
        writeString(MonitoringConstants.TECHNICAL_TRAINING_COL, rowHeader, "Technical Training");
        writeString(MonitoringConstants.NEW_PRACTICES_COL, rowHeader, "New Practices");
        writeString(MonitoringConstants.IMPROVED_PRACTICES_COL, rowHeader, "Improved Practices");
        writeString(MonitoringConstants.TRAINING_IMPROVEMENTS_COL, rowHeader, "Training Improvements");
        writeString(MonitoringConstants.BUSINESS_CHANGES_COL, rowHeader, "Business Changes");
        writeString(MonitoringConstants.PROFITABILITY_GROWTH_COL, rowHeader, "Profitability Growth");
        writeString(MonitoringConstants.REVENUE_CHANGE_COL, rowHeader, "Revenue Change");
        writeString(MonitoringConstants.LOAN_APPLICATION_COL, rowHeader, "Loan Application");
        writeString(MonitoringConstants.NUMBER_OF_LOANS_COL, rowHeader, "Number Of Loans");
        writeString(MonitoringConstants.LOAN_PLATFORM_COL, rowHeader, "Loan Platform");
        writeString(MonitoringConstants.EXTERNAL_FINANCING_COL, rowHeader, "External Financing");
        writeString(MonitoringConstants.FINANCING_SOURCES_COL, rowHeader, "Financing Sources");
        writeString(MonitoringConstants.JGP_IMPACT_COL, rowHeader, "JGP Impact");
        writeString(MonitoringConstants.CHANGES_WITHOUT_JGP_COL, rowHeader, "Changes Without JGP");
        writeString(MonitoringConstants.MARKET_ACCESS_COL, rowHeader, "Market Access");
        writeString(MonitoringConstants.BUSINESS_OPPORTUNITIES_COL, rowHeader, "Business Opportunities");
        writeString(MonitoringConstants.MARKET_CHALLENGES_COL, rowHeader, "Market Challenges");
    }
}

