ALTER TABLE loans
ADD COLUMN loan_amount_usd DECIMAL(19,4) NULL,
ADD COLUMN loan_amount_repaid DECIMAL(19,4) NULL,
ADD COLUMN loaner_type VARCHAR(150) DEFAULT NULL,
ADD COLUMN loan_type VARCHAR(150) DEFAULT NULL,
ADD COLUMN tranch_amount_allocated DECIMAL(19,4) NULL,
ADD COLUMN tranch_amount_disbursed DECIMAL(19,4) NULL,
ADD COLUMN loan_product VARCHAR(150) DEFAULT NULL;

ALTER TABLE bmo_participants_data ADD COLUMN training_partner VARCHAR(150) DEFAULT NULL,
ADD COLUMN ta_delivery_mode VARCHAR(150) DEFAULT NULL,
ADD COLUMN other_ta_needs VARCHAR(250) DEFAULT NULL,
ADD COLUMN ta_type VARCHAR(150) DEFAULT NULL;

ALTER TABLE participants ADD COLUMN passport VARCHAR(150) DEFAULT NULL;