CREATE TABLE outcome_monitoring (
	id                BIGINT GENERATED ALWAYS AS IDENTITY     NOT NULL,
	date_created timestamp DEFAULT CURRENT_TIMESTAMP,
	last_modified timestamp NULL,
    participant_id BIGINT NULL,
    survey_date date NOT NULL,
    survey_language VARCHAR(50) NULL,
    consented BOOLEAN NULL,
    location_latitude DECIMAL(19,10) NULL,
    location_longitude DECIMAL(19,10) NULL,
    age INT NULL,
    gender_category VARCHAR(50) NULL,
    segment VARCHAR(100) NULL,
    partner VARCHAR(100) NULL,
    gender VARCHAR(100) NULL,
    region VARCHAR(100) NULL,
    county_code VARCHAR(100) NULL,
    county_name VARCHAR(100) NULL,
    business_setting VARCHAR(100) NULL,
    business_age_category VARCHAR(100) NULL,
    group_membership VARCHAR(200) NULL,
    education_level VARCHAR(100) NULL,
    business_age INT NULL,
    regular_employees INT NULL,
    casual_employees INT NULL,
    household_income_change VARCHAR(100) NULL,
    financial_stability VARCHAR(100) NULL,
    quality_of_life VARCHAR(100) NULL,
    empowerment VARCHAR(100) NULL,
    voice_in_community VARCHAR(100) NULL,
    respect_in_community VARCHAR(100) NULL,
    reliable_income VARCHAR(100) NULL,
    reputable_work VARCHAR(100) NULL,
    sense_of_purpose VARCHAR(100) NULL,
    business_sector_growth VARCHAR(100) NULL,
    community_growth VARCHAR(100) NULL,
    work_opportunities VARCHAR(100) NULL,
    income_regularity VARCHAR(100) NULL,
    income_sufficiency VARCHAR(100) NULL,
    income_predictability VARCHAR(100) NULL,
    financial_security VARCHAR(100) NULL,
    community_groups VARCHAR(255) NULL,
    leadership_role VARCHAR(100) NULL,
    decision_making_confidence VARCHAR(100) NULL,
    community_change VARCHAR(100) NULL,
    community_issues VARCHAR(100) NULL,
    satisfaction_education VARCHAR(100) NULL,
    satisfaction_relationships VARCHAR(100) NULL,
    satisfaction_business_type VARCHAR(100) NULL,
    satisfaction_income VARCHAR(100) NULL,
    satisfaction_housing VARCHAR(100) NULL,
    satisfaction_healthcare VARCHAR(100) NULL,
    satisfaction_water VARCHAR(100) NULL,
    satisfaction_food VARCHAR(100) NULL,
    satisfaction_nutrition VARCHAR(100) NULL,
    satisfaction_life VARCHAR(100) NULL,
    satisfaction_information VARCHAR(100) NULL,
    satisfaction_leisure VARCHAR(100) NULL,
    jgp_interventions VARCHAR(255) NULL,
    technical_training VARCHAR(255) NULL,
    new_practices VARCHAR(255) NULL,
    improved_practices VARCHAR(255) NULL,
    training_improvements VARCHAR(200) NULL,
    business_changes VARCHAR(200) NULL,
    profitability_growth VARCHAR(200) NULL,
    revenue_change DECIMAL(19,4) NULL,
    loan_application VARCHAR(100) NULL,
    number_of_loans INT NULL,
    loan_platform VARCHAR(100) NULL,
    external_financing VARCHAR(100) NULL,
    financing_sources VARCHAR(255) NULL,
    jgp_impact VARCHAR(200) NULL,
    changes_without_jgp VARCHAR(255) NULL,
    market_access VARCHAR(255) NULL,
    business_opportunities VARCHAR(255) NULL,
    market_challenges VARCHAR(255) NULL,
	created_by_id BIGINT NULL,
	last_modified_by_id BIGINT NULL,
	CONSTRAINT monitor_pkey PRIMARY KEY (id),
	CONSTRAINT M_MONITOR_ON_MODIFIED_BY FOREIGN KEY (last_modified_by_id) REFERENCES users(id),
	CONSTRAINT M_MONITOR_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users(id),
	CONSTRAINT M_MONITOR_ON_PARTICIPANT FOREIGN KEY (participant_id) REFERENCES participants(id)
);


